# Write your MySQL query statement below
SELECT SUBSTRING_INDEX(SUBSTRING(tweet, LOCATE('#', tweet)), ' ', 1) AS HASHTAG, COUNT(*) AS HASHTAG_COUNT
FROM Tweets
GROUP BY 1
ORDER BY HASHTAG_COUNT DESC, HASHTAG DESC
LIMIT 3;